//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment_Requests
    {
        public int ID { get; set; }
        public string Symptoms { get; set; }
        public System.DateTime Request_Date { get; set; }
        public int ID_Patient { get; set; }

        public virtual Patient Patient { get; set; }
    }
}
