//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDoc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RWA2324_18_DBEntities : DbContext
    {
        public RWA2324_18_DBEntities()
            : base("name=RWA2324_18_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Appointment_Requests> Appointment_Requests { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Health_Catalog> Health_Catalog { get; set; }
        public virtual DbSet<Package_Services> Package_Services { get; set; }
        public virtual DbSet<Patient_Packages> Patient_Packages { get; set; }
        public virtual DbSet<Patient_Services> Patient_Services { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Service_Catalog> Service_Catalog { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
