//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDoc.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Patient_Packages
    {
        public int ID { get; set; }
        public Nullable<int> Used_Consultations { get; set; }
        public Nullable<int> Used_Blood_Extractions { get; set; }
        public int ID_Patient { get; set; }
        public int ID_Package_Catalog { get; set; }

        public virtual Health_Catalog Health_Catalog { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
