//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Card_Number { get; set; }
        public System.DateTime Exp_Date { get; set; }
        public int CVV { get; set; }
        public string JMBAG { get; set; }
        public Nullable<int> ID_Patient_Package { get; set; }
        public Nullable<int> ID_Patient_Service { get; set; }
        public int ID_Patient { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Patient Patient1 { get; set; }
        public virtual Patient Patient2 { get; set; }
    }
}
